[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"
  
  [[redirects]]
  from = "https://objective-pike-a47988.netlify.app/*"
  to = "https://adr.web.id/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
